import Head from "next/head";

function Home() {
  return (
    <div>
      <Head>
        <title> Create Next Apps</title>
        <meta name="discription" content="Generated by created next app" />
      </Head>

      <main className="wrapper">
        <h1> Data Fetching in Next.js 13</h1>
        <p>
          Data fetching in Next.js allows you to render your content in different ways, depending on
          your application's use case. These include pre-rendering with Server-side Rendering or
          Static Generation, and updating or creating content at runtime with Incremental Static
          Regeneration.
        </p>
      </main>
    </div>
  );
}

export default Home;
